name: Docs
on: [push]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - name: Install sphinx dependencies
        run: |
          pip install sphinx sphinx_rtd_theme
      - name: Sphinx build
        run: |
          sphinx-build -b html docs/source docs/build
          sphinx-build -b latex docs/source docs/build/latex
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: docs/build/latex/scrimp.tex
      - name: Deploy on GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          force_orphan: true
